### ISSUE TITLE
Workflow File

### ISSUE THREAD

**Issue by justnealpatel** [noelcody/quiver-fastsearch-alfred#1]
## Workflow Setup
Didn't know where to leave this, but where exactly is the workflow file? How can I get this running as a workflow? I also don't see the bash script you talk about in `README.md`.

**Comment by noelcody** [comment]
Hey, you can download the workflow from the [releases](https://github.com/noelcody/quiver-fastsearch-alfred/releases) page, just open that file up with Alfred. The bash script is in one of the workflow items, if you want you can see it in the info.plist that Alfred uses to build the workflow.

**Comment by justnealpatel** [comment]
Oh, I see! Thanks. Will be closing.
