### ISSUE TITLE
Open search result in existing quiver window

### ISSUE THREAD

**Issue by kleinjm** [noelcody/quiver-fastsearch-alfred#2]
Very fast and slick workflow but it's not great to have tons of windows open for each note. Any way to have the result open in an existing quiver window?

**Comment by noelcody** [comment]
I think this could be done using the app's url handler, something like `open quiver:///notes/{??}`

I'll look at adding this as a config option (or you could, feel free to PR).

**Comment by noelcody** [comment]
Currently unsupported in Quiver, have requested in https://github.com/HappenApps/Quiver/issues/1060. ~Closing this for now~ leaving open to see what happens with that issue.
