### ISSUE TITLE
How to define path with spaces

### ISSUE THREAD

**Issue by envas** [noelcody/quiver-fastsearch-alfred#3]
My path variable contains spaces. I tried to quote the path "/my/path with spaces/" or mask the space with \, nothing works. Any idea?

**Comment by kalebhermes** [comment]
try using backslashes before the space. Something like `/my/path\ with\ spaces/`. That's usually how a Unix system handles spaces in a path.

**Comment by envas** [comment]
That's what I did. Masking with `\` (sorry, git markdown deleted the backspace from my first comment). The script reports the following error `No such file or directory`, see the Albert debug.  The script splits the path variable, obviously, the script takes the path variable as literal and does not parse it before usage. The path is `/Users/Robert/Cloud\ Neopsis/Quiver`.

```
[15:13:23.325] Quiver Title Search[Script Filter] Queuing argument ''
[15:13:23.453] Quiver Title Search[Script Filter] Script with argv '(null)' finished
[15:13:23.456] STDERR: Quiver Title Search[Script Filter] find: /Users/Robert/Cloud\: No such file or directory
find: Neopsis/Quiver: No such file or directory
[15:13:23.457] Quiver Title Search[Script Filter] {"items": [
  
]}
```

I think it does not work in the shell, see this:

```
MBP-Robert:Cloud Neopsis Robert$ p=/Users/Robert/Cloud\ Neopsis
MBP-Robert:Cloud Neopsis Robert$ echo $p
/Users/Robert/Cloud Neopsis
MBP-Robert:Cloud Neopsis Robert$ x=`ls -l $p`
ls: /Users/Robert/Cloud: No such file or directory
MBP-Robert:Cloud Neopsis Robert$ 

```

**Comment by kalebhermes** [comment]
You can try unchecking `Backslaches` as an escape method in the script? I think maybe Alfred is escaping on the backslash in your path, and you want it to pass the whole thing down to the shell script. 

![](https://i.imgur.com/gVHrEFV.png)

**Comment by envas** [comment]
Escaping modifies only the {query} part. It does not modify anything in the script. The error message in the debug log appears immediately after pressing `q` before I enter any query. 

Maybe check this [link](https://unix.stackexchange.com/questions/444946/how-can-we-run-a-command-stored-in-a-variable/444949), there are some workarounds using functions or array.

**Comment by noelcody** [comment]
Updated with fix, download the new release and define your path with unescaped spaces.

`find "$path" -print0 | xargs -0 ...` is what's needed here. `"$path"` to use the path variable directly. `-print0 | xargs -0` to keep xargs from interpreting the space in find result as a delimiter (delimit on null character).
